# Generated by Django 2.0.2 on 2018-02-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
