# Generated by Django 2.0.2 on 2018-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aircraft_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
