# Generated by Django 2.0.2 on 2018-02-26 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180224_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumnail', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('homingType', models.CharField(max_length=200)),
                ('ammoType', models.CharField(max_length=200)),
                ('operationalRange', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('modelId', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='explanation',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='ammoSlot1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='ammoSlot2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='ammoSlot3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='boarding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='combatRadius',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='maxSpeed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='producer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='takeoffWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='thumnail',
            field=models.CharField(default='', max_length=300),
        ),
    ]
