# Generated by Django 2.0.2 on 2018-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180226_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='maxSpeed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
